name: Codecov Demo

#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
on:
  push:
    branches:
        ["master", fix/addingTests]
  pull_request:
    branches:
        ["master", fix/addingTests]
jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project CodecovDemo.xcodeproj -scheme CodecovDemo -destination 'platform=iOS Simulator,name=iPhone 11,OS= 13.3.1' build test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.2.1
